import '../models/exercise.dart';

class ExerciseData {
  static List<Exercise> get allExercises => _generatedExercises;

  static List<ExerciseCategory> get categories => ExerciseCategory.values;

  static final List<Exercise> _generatedExercises = _buildExercises();

  static List<Exercise> _buildExercises() {
    final templates = <_ExerciseTemplate>[
      _ExerciseTemplate(
        baseName: 'Jumping Jacks',
        description: 'Classic cardio move to raise heart rate quickly.',
        category: ExerciseCategory.cardio,
        muscles: ['Full Body', 'Legs', 'Shoulders'],
        equipment: 'None',
        instructions: 'Jump feet apart while lifting arms overhead, then return.',
        tips: 'Keep your core tight and land softly.',
        baseCalories: 18,
      ),
      _ExerciseTemplate(
        baseName: 'High Knees',
        description: 'Fast cardio drill for fat burn and coordination.',
        category: ExerciseCategory.hiit,
        muscles: ['Core', 'Legs'],
        equipment: 'None',
        instructions: 'Run in place while driving knees high.',
        tips: 'Pump your arms to keep rhythm.',
        baseCalories: 20,
      ),
      _ExerciseTemplate(
        baseName: 'Mountain Climbers',
        description: 'Core and cardio combination exercise.',
        category: ExerciseCategory.fullBody,
        muscles: ['Core', 'Shoulders', 'Legs'],
        equipment: 'None',
        instructions: 'From plank position, alternate knees toward chest.',
        tips: 'Avoid lifting hips too high.',
        baseCalories: 22,
      ),
      _ExerciseTemplate(
        baseName: 'Plank Hold',
        description: 'Foundational core strengthening movement.',
        category: ExerciseCategory.abs,
        muscles: ['Core', 'Shoulders', 'Lower Back'],
        equipment: 'None',
        instructions: 'Hold forearm plank with straight spine.',
        tips: 'Squeeze glutes and keep neck neutral.',
        baseCalories: 12,
      ),
      _ExerciseTemplate(
        baseName: 'Side Plank',
        description: 'Oblique-focused core stability hold.',
        category: ExerciseCategory.abs,
        muscles: ['Obliques', 'Core', 'Shoulders'],
        equipment: 'None',
        instructions: 'Balance on one forearm and side of foot.',
        tips: 'Stack hips and keep body in one line.',
        baseCalories: 11,
      ),
      _ExerciseTemplate(
        baseName: 'Russian Twists',
        description: 'Dynamic ab exercise targeting obliques.',
        category: ExerciseCategory.abs,
        muscles: ['Core', 'Obliques'],
        equipment: 'None',
        instructions: 'Twist torso side to side from seated balance position.',
        tips: 'Keep chest lifted throughout.',
        baseCalories: 14,
      ),
      _ExerciseTemplate(
        baseName: 'Crunches',
        description: 'Simple abdominal contraction exercise.',
        category: ExerciseCategory.abs,
        muscles: ['Upper Abs'],
        equipment: 'None',
        instructions: 'Lift shoulders off floor while keeping lower back controlled.',
        tips: 'Do not pull on your neck.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Bicycle Crunch',
        description: 'Alternating abdominal and oblique move.',
        category: ExerciseCategory.abs,
        muscles: ['Abs', 'Obliques'],
        equipment: 'None',
        instructions: 'Alternate elbow to opposite knee with pedaling legs.',
        tips: 'Move slowly for stronger contraction.',
        baseCalories: 16,
      ),
      _ExerciseTemplate(
        baseName: 'Leg Raises',
        description: 'Lower abdominal strengthening movement.',
        category: ExerciseCategory.abs,
        muscles: ['Lower Abs', 'Hip Flexors'],
        equipment: 'None',
        instructions: 'Lift straight legs up and lower with control.',
        tips: 'Keep lower back pressed down.',
        baseCalories: 13,
      ),
      _ExerciseTemplate(
        baseName: 'Flutter Kicks',
        description: 'Lower-core endurance exercise.',
        category: ExerciseCategory.abs,
        muscles: ['Lower Abs', 'Hip Flexors'],
        equipment: 'None',
        instructions: 'Alternate small leg kicks while lying on back.',
        tips: 'Keep your core braced.',
        baseCalories: 15,
      ),
      _ExerciseTemplate(
        baseName: 'Bodyweight Squats',
        description: 'Foundational lower-body strengthening exercise.',
        category: ExerciseCategory.legs,
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'None',
        instructions: 'Sit hips back and stand tall again.',
        tips: 'Keep knees tracking over toes.',
        baseCalories: 16,
      ),
      _ExerciseTemplate(
        baseName: 'Jump Squats',
        description: 'Explosive squat for power and fat burn.',
        category: ExerciseCategory.legs,
        muscles: ['Glutes', 'Quads', 'Calves'],
        equipment: 'None',
        instructions: 'Perform squat then jump explosively upward.',
        tips: 'Land softly and reset posture.',
        baseCalories: 24,
      ),
      _ExerciseTemplate(
        baseName: 'Forward Lunges',
        description: 'Unilateral exercise for legs and balance.',
        category: ExerciseCategory.legs,
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'None',
        instructions: 'Step forward, lower both knees, then return.',
        tips: 'Keep torso upright.',
        baseCalories: 15,
      ),
      _ExerciseTemplate(
        baseName: 'Reverse Lunges',
        description: 'Joint-friendly lunge variation.',
        category: ExerciseCategory.legs,
        muscles: ['Glutes', 'Quads', 'Hamstrings'],
        equipment: 'None',
        instructions: 'Step backward into lunge and return.',
        tips: 'Push through front heel.',
        baseCalories: 15,
      ),
      _ExerciseTemplate(
        baseName: 'Wall Sit',
        description: 'Isometric leg endurance challenge.',
        category: ExerciseCategory.legs,
        muscles: ['Quads', 'Glutes'],
        equipment: 'Wall',
        instructions: 'Slide down wall and hold seated position.',
        tips: 'Keep knees near 90 degrees.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Calf Raises',
        description: 'Simple lower-leg strengthening movement.',
        category: ExerciseCategory.legs,
        muscles: ['Calves'],
        equipment: 'None',
        instructions: 'Rise onto toes, pause, then lower slowly.',
        tips: 'Use full range of motion.',
        baseCalories: 8,
      ),
      _ExerciseTemplate(
        baseName: 'Glute Bridges',
        description: 'Glute activation and hip extension exercise.',
        category: ExerciseCategory.glutes,
        muscles: ['Glutes', 'Hamstrings'],
        equipment: 'None',
        instructions: 'Drive hips upward from lying position.',
        tips: 'Pause at top and squeeze glutes.',
        baseCalories: 11,
      ),
      _ExerciseTemplate(
        baseName: 'Donkey Kicks',
        description: 'Glute isolation floor exercise.',
        category: ExerciseCategory.glutes,
        muscles: ['Glutes'],
        equipment: 'None',
        instructions: 'Kick one heel upward while on all fours.',
        tips: 'Avoid arching the lower back.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Fire Hydrants',
        description: 'Hip and glute activation drill.',
        category: ExerciseCategory.glutes,
        muscles: ['Glute Medius', 'Outer Hips'],
        equipment: 'None',
        instructions: 'Lift knee to side from tabletop position.',
        tips: 'Keep hips square to the floor.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Step Ups',
        description: 'Functional lower-body movement.',
        category: ExerciseCategory.glutes,
        muscles: ['Glutes', 'Quads'],
        equipment: 'Bench or Step',
        instructions: 'Step onto stable platform and drive upward.',
        tips: 'Press through heel on the platform.',
        baseCalories: 17,
      ),
      _ExerciseTemplate(
        baseName: 'Push Ups',
        description: 'Classic upper-body compound exercise.',
        category: ExerciseCategory.chest,
        muscles: ['Chest', 'Triceps', 'Shoulders'],
        equipment: 'None',
        instructions: 'Lower chest toward floor and press back up.',
        tips: 'Keep body in a straight line.',
        baseCalories: 16,
      ),
      _ExerciseTemplate(
        baseName: 'Knee Push Ups',
        description: 'Beginner-friendly push-up variation.',
        category: ExerciseCategory.chest,
        muscles: ['Chest', 'Triceps'],
        equipment: 'None',
        instructions: 'Perform push-up from knees with controlled pace.',
        tips: 'Keep hips from sagging.',
        baseCalories: 11,
      ),
      _ExerciseTemplate(
        baseName: 'Chest Dips',
        description: 'Bodyweight pressing movement for chest and arms.',
        category: ExerciseCategory.chest,
        muscles: ['Chest', 'Triceps', 'Shoulders'],
        equipment: 'Chair',
        instructions: 'Lower body using arms and push back up.',
        tips: 'Keep shoulders away from ears.',
        baseCalories: 17,
      ),
      _ExerciseTemplate(
        baseName: 'Dumbbell Chest Press',
        description: 'Strength exercise for chest and triceps.',
        category: ExerciseCategory.dumbbell,
        muscles: ['Chest', 'Triceps'],
        equipment: 'Dumbbells',
        instructions: 'Press dumbbells upward from chest level.',
        tips: 'Control the lowering phase.',
        baseCalories: 18,
      ),
      _ExerciseTemplate(
        baseName: 'Superman Hold',
        description: 'Back extension movement for posture.',
        category: ExerciseCategory.back,
        muscles: ['Lower Back', 'Glutes', 'Upper Back'],
        equipment: 'None',
        instructions: 'Lift arms and legs slightly off floor and hold.',
        tips: 'Do not overextend the neck.',
        baseCalories: 9,
      ),
      _ExerciseTemplate(
        baseName: 'Bird Dog',
        description: 'Core and back stability movement.',
        category: ExerciseCategory.back,
        muscles: ['Core', 'Lower Back', 'Glutes'],
        equipment: 'None',
        instructions: 'Reach opposite arm and leg from tabletop.',
        tips: 'Move slowly and stay balanced.',
        baseCalories: 9,
      ),
      _ExerciseTemplate(
        baseName: 'Arm Circles',
        description: 'Shoulder warm-up and endurance drill.',
        category: ExerciseCategory.shoulders,
        muscles: ['Shoulders'],
        equipment: 'None',
        instructions: 'Make controlled circles with arms extended.',
        tips: 'Keep shoulders relaxed.',
        baseCalories: 8,
      ),
      _ExerciseTemplate(
        baseName: 'Pike Push Ups',
        description: 'Bodyweight shoulder-focused press.',
        category: ExerciseCategory.shoulders,
        muscles: ['Shoulders', 'Triceps'],
        equipment: 'None',
        instructions: 'Press upward from pike position.',
        tips: 'Lower head between hands with control.',
        baseCalories: 17,
      ),
      _ExerciseTemplate(
        baseName: 'Lateral Raises',
        description: 'Shoulder isolation with dumbbells.',
        category: ExerciseCategory.dumbbell,
        muscles: ['Side Delts'],
        equipment: 'Dumbbells',
        instructions: 'Raise arms to shoulder level then lower.',
        tips: 'Use light weight and strict form.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Tricep Dips',
        description: 'Chair-based triceps builder.',
        category: ExerciseCategory.arms,
        muscles: ['Triceps', 'Shoulders'],
        equipment: 'Chair',
        instructions: 'Lower body with elbows bent and press up.',
        tips: 'Keep elbows pointing backward.',
        baseCalories: 13,
      ),
      _ExerciseTemplate(
        baseName: 'Diamond Push Ups',
        description: 'Push-up variation targeting triceps.',
        category: ExerciseCategory.arms,
        muscles: ['Triceps', 'Chest'],
        equipment: 'None',
        instructions: 'Hands close together under chest, then press.',
        tips: 'Use knees if needed.',
        baseCalories: 18,
      ),
      _ExerciseTemplate(
        baseName: 'Bicep Curls',
        description: 'Dumbbell arm exercise.',
        category: ExerciseCategory.dumbbell,
        muscles: ['Biceps'],
        equipment: 'Dumbbells',
        instructions: 'Curl weights upward without swinging.',
        tips: 'Keep elbows near ribs.',
        baseCalories: 10,
      ),
      _ExerciseTemplate(
        baseName: 'Burpees',
        description: 'Full-body fat burning compound move.',
        category: ExerciseCategory.hiit,
        muscles: ['Full Body'],
        equipment: 'None',
        instructions: 'Drop down, jump back, return up, and explode.',
        tips: 'Keep a steady rhythm.',
        baseCalories: 28,
      ),
      _ExerciseTemplate(
        baseName: 'Skaters',
        description: 'Lateral cardio exercise for agility and burn.',
        category: ExerciseCategory.cardio,
        muscles: ['Glutes', 'Legs', 'Core'],
        equipment: 'None',
        instructions: 'Leap side to side while balancing.',
        tips: 'Stay low and controlled.',
        baseCalories: 19,
      ),
      _ExerciseTemplate(
        baseName: 'Fast Feet',
        description: 'Quick cardio movement to raise heart rate.',
        category: ExerciseCategory.cardio,
        muscles: ['Legs', 'Calves'],
        equipment: 'None',
        instructions: 'Move feet quickly in place with bent knees.',
        tips: 'Stay light on your feet.',
        baseCalories: 18,
      ),
      _ExerciseTemplate(
        baseName: 'Butt Kicks',
        description: 'Simple cardio move and warm-up drill.',
        category: ExerciseCategory.warmup,
        muscles: ['Hamstrings', 'Calves'],
        equipment: 'None',
        instructions: 'Jog in place while kicking heels toward glutes.',
        tips: 'Keep chest tall.',
        baseCalories: 14,
      ),
      _ExerciseTemplate(
        baseName: 'Torso Twists',
        description: 'Mobility drill for trunk rotation.',
        category: ExerciseCategory.mobility,
        muscles: ['Core', 'Spine Mobility'],
        equipment: 'None',
        instructions: 'Rotate torso side to side with relaxed arms.',
        tips: 'Move gently and do not force range.',
        baseCalories: 6,
      ),
      _ExerciseTemplate(
        baseName: 'Hip Openers',
        description: 'Mobility movement for hips and lower body.',
        category: ExerciseCategory.mobility,
        muscles: ['Hips', 'Glutes'],
        equipment: 'None',
        instructions: 'Lift and rotate knees outward in a controlled way.',
        tips: 'Maintain balance and smooth motion.',
        baseCalories: 6,
      ),
      _ExerciseTemplate(
        baseName: 'Cat Cow Stretch',
        description: 'Spinal mobility and breathing exercise.',
        category: ExerciseCategory.stretching,
        muscles: ['Spine', 'Core'],
        equipment: 'None',
        instructions: 'Alternate arching and rounding the back.',
        tips: 'Sync movement with breathing.',
        baseCalories: 5,
      ),
      _ExerciseTemplate(
        baseName: 'Child Pose Stretch',
        description: 'Relaxing stretch for back and hips.',
        category: ExerciseCategory.stretching,
        muscles: ['Back', 'Hips', 'Shoulders'],
        equipment: 'None',
        instructions: 'Sit back on heels and extend arms forward.',
        tips: 'Breathe deeply into your back.',
        baseCalories: 4,
      ),
      _ExerciseTemplate(
        baseName: 'Hamstring Stretch',
        description: 'Static stretch for back of legs.',
        category: ExerciseCategory.stretching,
        muscles: ['Hamstrings'],
        equipment: 'None',
        instructions: 'Reach toward extended leg while keeping back long.',
        tips: 'Avoid bouncing.',
        baseCalories: 4,
      ),
      _ExerciseTemplate(
        baseName: 'Quad Stretch',
        description: 'Stretch front thigh muscles.',
        category: ExerciseCategory.stretching,
        muscles: ['Quads'],
        equipment: 'None',
        instructions: 'Pull heel gently toward glute while standing.',
        tips: 'Use wall for balance if needed.',
        baseCalories: 4,
      ),
      _ExerciseTemplate(
        baseName: 'Shoulder Rolls',
        description: 'Simple posture and tension relief movement.',
        category: ExerciseCategory.posture,
        muscles: ['Shoulders', 'Upper Traps'],
        equipment: 'None',
        instructions: 'Roll shoulders back and down slowly.',
        tips: 'Do not rush the movement.',
        baseCalories: 4,
      ),
      _ExerciseTemplate(
        baseName: 'Wall Angels',
        description: 'Excellent posture and upper-back drill.',
        category: ExerciseCategory.posture,
        muscles: ['Upper Back', 'Shoulders'],
        equipment: 'Wall',
        instructions: 'Slide arms up and down on wall while staying aligned.',
        tips: 'Keep lower ribs tucked.',
        baseCalories: 7,
      ),
      _ExerciseTemplate(
        baseName: 'Dead Bug',
        description: 'Deep-core stability movement.',
        category: ExerciseCategory.abs,
        muscles: ['Core', 'Lower Abs'],
        equipment: 'None',
        instructions: 'Lower opposite arm and leg while keeping core braced.',
        tips: 'Keep lower back stable.',
        baseCalories: 10,
      ),
    ];

    final variations = <_Variation>[
      _Variation(
        suffix: 'Beginner',
        difficulty: ExerciseDifficulty.beginner,
        durationSeconds: 30,
        calorieMultiplier: 1.0,
      ),
      _Variation(
        suffix: 'Intermediate',
        difficulty: ExerciseDifficulty.intermediate,
        durationSeconds: 45,
        calorieMultiplier: 1.25,
      ),
      _Variation(
        suffix: 'Advanced',
        difficulty: ExerciseDifficulty.advanced,
        durationSeconds: 60,
        calorieMultiplier: 1.55,
      ),
      _Variation(
        suffix: 'Endurance',
        difficulty: ExerciseDifficulty.advanced,
        durationSeconds: 90,
        calorieMultiplier: 1.9,
      ),
      _Variation(
        suffix: 'Quick Burn',
        difficulty: ExerciseDifficulty.intermediate,
        durationSeconds: 40,
        calorieMultiplier: 1.2,
      ),
    ];

    final List<Exercise> exercises = [];
    int counter = 1;

    for (final template in templates) {
      for (final variation in variations) {
        exercises.add(
          Exercise(
            id: 'ex_${counter.toString().padLeft(3, '0')}',
            name: '${template.baseName} ${variation.suffix}',
            description: template.description,
            category: template.category,
            difficulty: variation.difficulty,
            durationSeconds: variation.durationSeconds,
            caloriesBurnEstimate:
                (template.baseCalories * variation.calorieMultiplier).round(),
            targetMuscles: template.muscles,
            equipmentRequired: template.equipment.toLowerCase() != 'none',
            equipment: template.equipment,
            instructions: template.instructions,
            tips: template.tips,
          ),
        );
        counter++;
      }
    }

    return exercises;
  }
}

class _ExerciseTemplate {
  final String baseName;
  final String description;
  final ExerciseCategory category;
  final List<String> muscles;
  final String equipment;
  final String instructions;
  final String tips;
  final int baseCalories;

  const _ExerciseTemplate({
    required this.baseName,
    required this.description,
    required this.category,
    required this.muscles,
    required this.equipment,
    required this.instructions,
    required this.tips,
    required this.baseCalories,
  });
}

class _Variation {
  final String suffix;
  final ExerciseDifficulty difficulty;
  final int durationSeconds;
  final double calorieMultiplier;

  const _Variation({
    required this.suffix,
    required this.difficulty,
    required this.durationSeconds,
    required this.calorieMultiplier,
  });
}
